name: Deploy Python app to EC2

on:
  push:
    branches:
     - master


jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Deploy via SSH
            uses: appleboy/ssh-action@v1.0.3
            with: 
               host: ${{secrets.EC2_HOST}}
               username: ubuntu
               key: ${{secrets.EC2_SSH_KEY}}
               script: |
                 cd /home/ubuntu/Docker_and_CICD
                 git pull -u origin master
                 sudo docker compose up -d --build